### ISSUE TITLE
Vague oserror on deploy_python_closure

### ISSUE THREAD

**Issue by itobysq** [ucbrise/clipper#676] opened 2019-04-24 16:00 UTC
Thanks for building clipper! It's a very compelling idea. When I call a model inside of a function, the function that deploy_python_closure references fails and provides a vague `OSError: Invalid Argument` I tried adding the scipy, numpy and sci-kit learn to the closure based on this [issue:](https://github.com/ucbrise/clipper/issues/546) and I get the same error.

Can someone please provide a hint as to what the error is referencing? 

I was hoping to access the model via closure capture like [in this example](http://docs.clipper.ai/en/v0.3.0/model_deployers.html#clipper_admin.deployers.python.deploy_python_closure) but it's not working for me.

Here's a snippet of code
```
clipper_conn = ClipperConnection(DockerContainerManager())
clipper_conn.start_clipper()
clipper_conn.register_application(name="hello-world",
                                    input_type="ints",
                                    default_output="-1.0",
                                    slo_micros=100000000)

suggester = nb.ArticleSuggester()
suggester.build_article_solution_table(title_solution_fname='title_map.csv')
model = RandomForestClassifier(n_estimators=10)
suggester.train_model(model, 'test_model.joblib')

def feature_sum(xs):
    title_map='title_map.csv'
    issue_counts_fpath='../../tests/issue_counts.csv'
    firmware = inputs[0]
    issue_articles = inputs[1:]
    session_article_vector = np.zeros((1, model.n_features_ - 1))
    for article_id in issue_articles:
        session_article_vector[0][article_id] = 1
    sample_vector = np.concatenate([session_article_vector, np.array([[firmware]])], axis=1)
    probas = model.predict_proba(sample_vector)

    return [str(sum(x)) for x in xs]

try:
    deploy_python_closure(clipper_conn, version="v1-3", name="suggest-example",input_type="integers",func=feature_sum)
    clipper_conn.link_model_to_app(app_name="hello-world", model_name="suggest-example")
```

**Comment by rkooo567** [comment] 2019-04-24 17:26
Hi, @itobysq. Thank you for raising an issue. 

OSError is an error from syscall I believe, and I couldn't find OSError catching clause from Clipper. I guess it is from the function itself. Would you mind showing us 

1. The logs of  `deploy_python_closure` (the script you posted)
2. The docker logs of python closure model (If you succeed to deploy the model)?

**Comment by itobysq** [comment] 2019-04-24 23:59
I don't believe the docker logs of python closure model exist. The containers that are running at failure are `metric_frontend-17595, query_frontend_exporter-75917, query_frontend-75917, mgmt_frontend-10929, and redis-26171`

The log message when I step through the code is 
```
-> deploy_python_closure(clipper_conn, version="v1-3", name="suggest-example",input_type="integers",func=feature_sum)
(Pdb) n
19-04-24:16:46:14 INFO     [deployer_utils.py:44] Saving function to /tmp/clipper/tmp94973q9e
OSError: [Errno 22] Invalid argument
> redacted/file/path/clipper_client.py(85)<module>()
-> deploy_python_closure(clipper_conn, version="v1-3", name="suggest-example",input_type="integers",func=feature_sum)
(Pdb) c
19-04-24:16:57:08 INFO     [clipper_admin.py:1258] Stopped all Clipper cluster and all model containers
```

**Comment by rkooo567** [comment] 2019-04-25 06:30
Seems like the program is broken at this function. 
```python3
def save_python_function(name, func):
    predict_fname = "func.pkl"

    # Serialize function
    s = StringIO()
    c = CloudPickler(s, 2)
    c.dump(func)
    serialized_prediction_function = s.getvalue()

    # Set up serialization directory
    serialization_dir = os.path.abspath(tempfile.mkdtemp(suffix='clipper'))
    logger.info("Saving function to {}".format(serialization_dir))

    # Write out function serialization
    func_file_path = os.path.join(serialization_dir, predict_fname)
    if sys.version_info < (3, 0):
        with open(func_file_path, "w") as serialized_function_file:
            serialized_function_file.write(serialized_prediction_function)
    else:
        with open(func_file_path, "wb") as serialized_function_file:
            serialized_function_file.write(serialized_prediction_function)
    logging.info("Serialized and supplied predict function")
    return serialization_dir
```

As you can see, there is a line that calls a syscall. 
```python3
        with open(func_file_path, "wb") as serialized_function_file:
            serialized_function_file.write(serialized_prediction_function)
```

So there's a problem with `open` function. 

What I found online is https://bugs.python.org/issue29097. Are you using python 3.6? If so, can you try to update it to python3.6.7 and retry?

**Comment by rkooo567** [comment] 2019-04-25 06:46
Couple other reasons can be 

1. `/tmp/clipper/tmp94973q9e` has too huge size. Can you cd to the dir and see the file if it exists? if so can you check the size? https://stackoverflow.com/questions/48122798/oserror-errno-22-invalid-argument-when-reading-a-huge-file
2. Absolute path created by clipper has a illegal character (I really doubt it, but it can be possible). If so, can you try downloading `develop` version of python and try running your script with that?

**Comment by itobysq** [comment] 2019-04-26 23:11
Thank you for looking into this @rkooo567. I had a chance to try your suggestions.
1. I tried using Python 3.6.7 and still have the issue. 
2. I could not see the file in `tmp/clipper/` because I believe the file failed to write. I suspect that the problem is that the file is still too big. The model saved in joblib is 4GB. What is the limit for the size of a clipper model?
3. Sorry I am not clear on what you mean by the "develop version of python" if you think it's still important to try this, can you please provide a link to the develop version of Python? Thanks!

**Comment by rkooo567** [comment] 2019-04-27 03:53
@itobysq Sorry about 3. What I meant was `develop` version of clipper not python. But I don't think it will help. 

https://bugs.python.org/issue24658. As you can see from here, python used to have problems reading/writing more than 2GB files, but seems like it should've been resolved. Can you try creating a smaller size model and run the code again if you don't mind? If it is the issue, we probably need a patch for that.  

The other possibility is that you are using jupyter notebook and file is corrupted somehow because you run the parts of your code. Are you using the jupyter notebook? 

Also, @RehanSD @simon-mo @withsmilo. Please let me know if you guys have seen similar bugs before.

**Comment by itobysq** [comment] 2019-04-30 22:06
I was able to deploy the closure with a model that is only 1.3G instead of 4G. The reduced size does affect my model's performance, unfortunately. I am not running the code in a notebook. I am running the code in a python script.

You are right, I think there needs to be a patch for bigger models if you choose to support them.

**Comment by rkooo567** [comment] 2019-05-01 01:30
@itobysq Thank you for the verification! 

I will create an issue about this, and we will fix it in the next release. Also, feel free to create a PR if you would like to solve the problem!

**Comment by withsmilo** [comment] 2019-05-04 16:09
@itobysq @rkooo567 : I'm so sorry for late reply. How about try to use Python 3.6.8?

**Comment by rkooo567** [comment] 2019-05-10 15:12
@itobysq https://github.com/ucbrise/clipper/issues/681

Can you try python 3.6.8?

**Comment by itobysq** [comment] 2019-05-21 18:58
Sorry for the delay, got caught up in some things. I'm running into an issue
```
Starting managed Redis instance in Docker
docker.errors.APIError: 502 Server Error: Bad Gateway ("b'Mounts denied: \r\nThe path /tmp/clipper/prometheus.yml\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'")
```
Docker preferences lists /tmp/clipper/ and /tmp/clipper as being able to be bind mounted and it's unclear to me why this error is popping up.

**Comment by withsmilo** [comment] 2019-05-21 23:13
<img width="493" alt="mac_docker_preferences" src="https://user-images.githubusercontent.com/3915543/58136540-60442600-7c69-11e9-92fd-c65bf28a0a39.png">
This is my Docker preferences. Do you have `/tmp/clipper/` in it?

**Comment by rkooo567** [comment] 2019-05-28 04:52
Hi, @itobysq. Would you be able to resolve the issue?

**Comment by itobysq** [comment] 2019-05-28 05:12
Yes, I have /tmp/clipper/ in it as well as /private/tmp/clipper

**Comment by rkooo567** [comment] 2019-05-28 05:57
@itobysq Sounds good! I will close the issue then.

**Closed as completed by rkooo567** 2019-05-28 05:57 UTC

**Comment by itobysq** [comment] 2019-05-30 15:48
@rkooo567  it looks like we posted at exactly the same time. This is still an issue. My yes was in reference to @withsmilo 's comment. The issue is not closed, sorry.

**Comment by rkooo567** [comment] 2019-05-31 03:08
@itobysq My bad! Would you mind creating a new issue since the issue is unrelated to the title? (So that people can easily search later when they have the same issue).
