### ISSUE TITLE
Restart clipper containers and app containers on server reboot

### ISSUE THREAD

**Issue by rmdort** [ucbrise/clipper#155] opened 2017-05-13 05:11 UTC
Upon server reboot, can we restart

1. Clipper containers - I think this can be by adding `restart:always` to `docker-compose.yaml` file
2. Model containers - If a model is currently active, can we restart the specific containers. Not sure how this can be done.

Can we also move redis storage to a persistent volume in docker-compose. I think i saw a discussion about this on your Jira, but the issue was closed.

````
services:
  redis:
     volumes:
          - redisdata:/data
````

**Comment by dcrankshaw** [comment] 2017-05-20 03:52
Fixed by #161

**Comment by rmdort** [comment] 2017-05-20 09:09
Something is not working right. The redis path is not persisted after reboot.

Scenario
1. Run clipper
2. Register an application and deploy a model
3. Hard reboot server
4. Clipper containers are relaunched automatically

`clipper.get_all_apps()` shows zero applications

Is this anything to do with `redis_persistence_path` ? I am connecting to clipper using the below command

````
clipper = cm.Clipper(host, user, key, redis_persistence_path='/tmp/clipper_redis_data')
````

**Comment by dcrankshaw** [comment] 2017-05-20 16:17
@rmdort Can you verify that `/tmp/clipper_redis_data` still exists when you reboot the server? Often, `/tmp` gets cleared on reboot, so you may want to use a different path to persist the data.

**Comment by rmdort** [comment] 2017-05-21 04:53
Yes it does get removed. I have tried setting redis_persistence_path to `/data/clipper_redis_data` . But on reboot, redis doesn't read from this path.

**Comment by dcrankshaw** [comment] 2017-06-16 21:42
The outstanding issue here is a Redis related issue that is a duplicate of #216. Closing.

**Closed as completed by dcrankshaw** 2017-06-16 21:42 UTC
