### ISSUE TITLE
[CI] Two or more Jenkins jobs might make the whole unstable

### ISSUE THREAD

**Issue by withsmilo** [ucbrise/clipper#702] opened 2019-05-20 22:24 UTC
I found that when we executed two or more Jenkins jobs almost simultaneously, all the jobs were unstable with a high probability.
* May 20, 2019 7:22 AM : https://amplab.cs.berkeley.edu/jenkins/job/Clipper-PRB/2003/
* May 20, 2019 7:20 AM : https://amplab.cs.berkeley.edu/jenkins/job/Clipper-PRB/2002/
* May 20, 2019 7:19 AM : https://amplab.cs.berkeley.edu/jenkins/job/Clipper-PRB/2001/
* May 20, 2019 7:16 AM : https://amplab.cs.berkeley.edu/jenkins/job/Clipper/4394/

Where is bottleneck? Anyway, to avoid this situation, we have to execute one by one.

**Comment by rkooo567** [comment] 2019-05-21 05:26
I think one of the causes can be because our clusters are not well isolated. The first 3 CI runs in the same worker machine, and 3 of them have request related errors. 

@simon-mo and I discussed about it, and he will probably try to use docker-in-docker for testing isolation. Also, I will change `test_util` to use fluentd instead of naive docker logs. By this, we can see aggregated logs in timely order. It will help us debug what is the problem.

**Comment by rkooo567** [comment] 2019-05-21 05:29
Also, since the 4th job was ran in a different worker, I am not sure if the error is due to simultaneous jobs with other 3. 

It seems like it is broken with `address already in use`. I think port conflicts rarely happen. To solve this, we can probably use `lsof` or `netstat` to check available port instead of assigning random port. 
EDIT -> This part is just resolved by retrying I think

**Comment by simon-mo** [comment] 2019-05-21 07:53
I throttled the builds to 1 per node and made sure the the clipper main build and pull request builder share the same throttling parameter. We will see if this helps.

**Comment by simon-mo** [comment] 2019-05-21 08:03
Let's keep this issue open for few more days. So right now there are three builds running, each on different nodes:
- worker-07: https://amplab.cs.berkeley.edu/jenkins/job/Clipper-PRB/2009/
- worker-02: https://amplab.cs.berkeley.edu/jenkins/job/Clipper-PRB/2010/
- worker-08: https://amplab.cs.berkeley.edu/jenkins/job/Clipper-PRB/2011/

This is the behavior we wanted. But not sure if the collision will happen again.

**Comment by rkooo567** [comment] 2019-05-29 03:28
@withsmilo @simon-mo I think it will be resolved by this. https://github.com/ucbrise/clipper/issues/709 Can I close?

**Comment by simon-mo** [comment] 2019-05-29 03:39
Yes this can be closed.

**Closed as completed** 2019-05-29 04:55 UTC
Labels: type: maintenance
