### ISSUE TITLE
Failing tests when executing run_unittests.sh

### ISSUE THREAD

**Issue by lucasmoura** [ucbrise/clipper#105] opened 2017-04-03 17:21 UTC
Some tests appear to fail when executing the run_unittests.sh script, but in the end, it appears that all the tests were executed without any errors. This can be seen on the following image:

![broken_tests](https://cloud.githubusercontent.com/assets/2703696/24621751/fb3fdc8c-1878-11e7-975b-d5fb4cde80f6.png)

This is also happening in the project build. Is that the expected behavior, or should these tests break the current build ?

**Comment by dcrankshaw** [comment] 2017-04-03 22:29
This is not expected behavior. Unfortunately there was a bug in our run_unittests script which meant that it wasn't exiting on error so broken unit tests snuck in. I have fixed the bug but it means the build is broken.

@Corey-Zumar I believe this is due to your changes to the RPC format in #97. Can you fix this?

**Comment by Corey-Zumar** [comment] 2017-04-03 22:47
Yep, on it!

**Comment by Corey-Zumar** [comment] 2017-04-04 00:19
The failure of `WhenEitherTests.EntryAlreadyComplete` should not have been affected by #97. @dcrankshaw can you take a look at this? 

I've opened #107 to fix the input serialization tests.

**Comment by dcrankshaw** [comment] 2017-04-04 01:16
Fixed by #107

**Closed as completed by dcrankshaw** 2017-04-04 01:16 UTC

**Comment by dcrankshaw** [comment] 2017-04-04 01:17
I don't see that test failing. Maybe it's flaky?

**Comment by Corey-Zumar** [comment] 2017-04-04 01:23
I think it is. Can't seem to get it to fail either.
